#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("E4_xamarin.Resource", IsApplication=true)]

namespace E4_xamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040025
			public const int btnExit = 2130968613;
			
			// aapt resource value: 0x7f040024
			public const int btnInserePosseder = 2130968612;
			
			// aapt resource value: 0x7f04002c
			public const int btnInsererSPEdePRT = 2130968620;
			
			// aapt resource value: 0x7f040003
			public const int btnInsertSPE = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int btnInvite = 2130968576;
			
			// aapt resource value: 0x7f040017
			public const int btnSPAdePRT = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int btnSPE = 2130968598;
			
			// aapt resource value: 0x7f04001c
			public const int btnValider = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int lstActivite = 2130968603;
			
			// aapt resource value: 0x7f040005
			public const int lstActivites = 2130968581;
			
			// aapt resource value: 0x7f040019
			public const int lstPraticien = 2130968601;
			
			// aapt resource value: 0x7f04002d
			public const int lstPraticienPOS = 2130968621;
			
			// aapt resource value: 0x7f040002
			public const int lstPraticientInviter = 2130968578;
			
			// aapt resource value: 0x7f04001d
			public const int lstPratisienNEWPOS = 2130968605;
			
			// aapt resource value: 0x7f040004
			public const int lstSPE = 2130968580;
			
			// aapt resource value: 0x7f040028
			public const int lstSPEdePRA = 2130968616;
			
			// aapt resource value: 0x7f04001f
			public const int lstSpecialiteNEWPOSS = 2130968607;
			
			// aapt resource value: 0x7f04001a
			public const int s = 2130968602;
			
			// aapt resource value: 0x7f040018
			public const int sd = 2130968600;
			
			// aapt resource value: 0x7f040001
			public const int textView1 = 2130968577;
			
			// aapt resource value: 0x7f04001e
			public const int textView2 = 2130968606;
			
			// aapt resource value: 0x7f040020
			public const int textView3 = 2130968608;
			
			// aapt resource value: 0x7f040022
			public const int textView4 = 2130968610;
			
			// aapt resource value: 0x7f040026
			public const int txtCodeDialogINS = 2130968614;
			
			// aapt resource value: 0x7f040011
			public const int txtCodeSPE = 2130968593;
			
			// aapt resource value: 0x7f040023
			public const int txtCoef = 2130968611;
			
			// aapt resource value: 0x7f040010
			public const int txtCoefItemPOS = 2130968592;
			
			// aapt resource value: 0x7f040009
			public const int txtDate = 2130968585;
			
			// aapt resource value: 0x7f040021
			public const int txtDiplome = 2130968609;
			
			// aapt resource value: 0x7f04000f
			public const int txtDiplomeItemPOS = 2130968591;
			
			// aapt resource value: 0x7f040029
			public const int txtIdPRAIteme = 2130968617;
			
			// aapt resource value: 0x7f040012
			public const int txtLiballeSPE = 2130968594;
			
			// aapt resource value: 0x7f040027
			public const int txtLibelleDialogINS = 2130968615;
			
			// aapt resource value: 0x7f04000d
			public const int txtLieu = 2130968589;
			
			// aapt resource value: 0x7f040008
			public const int txtLieuItem = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int txtMotif = 2130968588;
			
			// aapt resource value: 0x7f040007
			public const int txtMotifItem = 2130968583;
			
			// aapt resource value: 0x7f04002b
			public const int txtNomPRAItem = 2130968619;
			
			// aapt resource value: 0x7f04002a
			public const int txtPrenomPRAItem = 2130968618;
			
			// aapt resource value: 0x7f04000a
			public const int txtSpecialist = 2130968586;
			
			// aapt resource value: 0x7f04000e
			public const int txtSpecialiteItemPOS = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int txtSpinerID = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int txtSpinerPrenom = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int txtSpinnerNom = 2130968597;
			
			// aapt resource value: 0x7f04000b
			public const int txtTheme = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int txtThemeItem = 2130968582;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int GestionInvit_layout = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int GestionSpecialite_layout = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Inviter_layout = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ItemActivite = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ItemActiviteInv = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ItemPosseder = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ItemSpecialite = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ItemSpinner = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Main = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int newInviter_layout = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int newSpecialiteDePraticienDialog_layout = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int newSpecialiteDialogLayout = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Posseder_layout = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int PraticienItem = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int SpecialiteDePraticien_layout = 2130837518;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ip = 2130903041;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
